language: node_js
services:
  - docker
before_install:
    - docker run --name todo_neo4j -p7474:7474 -p7687:7687 -d --env NEO4J_AUTH=neo4j/test neo4j:latest 
node_js:
    - "stable"
install:
    - yarn --cwd ./todo-list install
    - yarn --cwd ./todo-list-backend install
script:
    - yarn --cwd ./todo-list test:unit
    - yarn --cwd ./todo-list lint
    - yarn --cwd ./todo-list-backend test:integration
