language: node_js
node_js:
    - "stable"
install:
    - yarn --cwd ./todo-list install
    - yarn --cwd ./todo-list-backend install
script:
    - yarn --cwd ./todo-list test:unit
    - yarn --cwd ./todo-list lint
    - yarn --cwd ./todo-list-backend test:integration
